# Generated by Django 3.1.7 on 2021-04-18 17:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=10)),
                ('production_year', models.IntegerField()),
                ('avg_fuel_consumption_per_100km', models.FloatField()),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('max_passengers', models.IntegerField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
